### ISSUE TITLE
hugo new panics when folder name contains a date

### ISSUE THREAD

**Issue by pawelgrzybek** [gohugoio/hugo#12599]
### What version of Hugo are you using (`hugo version`)?

<pre>
hugo v0.127.0+extended darwin/arm64 BuildDate=2024-06-05T10:27:59Z VendorInfo=brew
</pre>

### Does this issue reproduce with the latest release?

Yes

- - -

I use leaf bundles for my `posts`. I infer `date` of my posts from the folder name. I have this in my config.

```
[frontmatter]
  date = [':filename', ':default']
```

Assuming I have this archetype under `archetypes/posts/index.md`

```
---
title: "Title goes here"
summary: "Summary goes here."
---
```

When I run `hugo new posts/test` it works as expected. If I run a `hugo new posts/2024-06-17-test`, I am receiving an error.

```
panic: [BUG] no Page found for "/Users/pawelgrzybek/Sites/pawelgrzybek.com/content/posts/2024-06-17-test/index.md"

goroutine 1 [running]:
github.com/gohugoio/hugo/create.(*contentBuilder).applyArcheType(0x14000b2ccc0, {0x14000b0b200, 0x59}, {0x104034360, 0x14000373140})
	github.com/gohugoio/hugo/create/content.go:273 +0x2b8
github.com/gohugoio/hugo/create.(*contentBuilder).buildDir(0x14000b2ccc0)
	github.com/gohugoio/hugo/create/content.go:179 +0x51c
github.com/gohugoio/hugo/create.NewContent.func1()
	github.com/gohugoio/hugo/create/content.go:92 +0x268
github.com/gohugoio/hugo/create.NewContent(0x140009b6000, {0x0, 0x0}, {0x16f9b3a79, 0x15}, 0x0)
	github.com/gohugoio/hugo/create/content.go:106 +0x480
github.com/gohugoio/hugo/commands.newNewCommand.func1({0x0?, 0x0?}, 0x0?, 0x140008a8c80, {0x140008f1250, 0x0?, 0x0?})
	github.com/gohugoio/hugo/commands/new.go:60 +0x160
github.com/gohugoio/hugo/commands.(*simpleCommand).Run(0x0?, {0x1040292e8?, 0x105475840?}, 0x0?, {0x140008f1250?, 0xa6fa80a000000000?, 0x140008059f8?})
	github.com/gohugoio/hugo/commands/commandeer.go:618 +0x48
github.com/bep/simplecobra.(*Commandeer).compile.func1(0x140006c3000?, {0x140008f1250?, 0x4?, 0x1021ccd37?})
	github.com/bep/simplecobra@v0.4.0/simplecobra.go:113 +0x54
github.com/spf13/cobra.(*Command).execute(0x140008faf08, {0x140008f1210, 0x1, 0x1})
	github.com/spf13/cobra@v1.8.0/command.go:983 +0x840
github.com/spf13/cobra.(*Command).ExecuteC(0x1400056b208)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).ExecuteContextC(...)
	github.com/spf13/cobra@v1.8.0/command.go:1048
github.com/bep/simplecobra.(*Exec).Execute(0x14000091320, {0x1040292e8?, 0x105475840?}, {0x140002b0a80?, 0x103bb7e40?, 0x100496028?})
	github.com/bep/simplecobra@v0.4.0/simplecobra.go:155 +0xb4
github.com/gohugoio/hugo/commands.Execute({0x1400004e4c0, 0x2, 0x2})
	github.com/gohugoio/hugo/commands/commandeer.go:68 +0x284
main.main()
	github.com/gohugoio/hugo/main.go:25 +0x70
```

Here is a repo where I am facing this issue: https://github.com/pawelgrzybek/pawelgrzybek.com

**Comment by jmooring** [comment]
Problem occurs with v0.123.0 and later.

**Comment by pawelgrzybek** [comment]
Thanks for confirming that @jmooring

**Comment by khayyamsaleem** [comment]
Unable to reproduce with v0.128.2

**Comment by pawelgrzybek** [comment]
Just tested on v0.128.2 and bug is still there.

```
~/Sites/pawelgrzybek.com hugo new posts/2024-08-17-test                                                                                                                                                                                                               master:386022ac [•]
panic: [BUG] no Page found for "/Users/pawelgrzybek/Sites/pawelgrzybek.com/content/posts/2024-08-17-test/index.md"

goroutine 1 [running]:
github.com/gohugoio/hugo/create.(*contentBuilder).applyArcheType(0x14000a32d80, {0x14000193da0, 0x51}, {0x10420ff40, 0x14000373740})
	github.com/gohugoio/hugo/create/content.go:273 +0x2b8
github.com/gohugoio/hugo/create.(*contentBuilder).buildDir(0x14000a32d80)
	github.com/gohugoio/hugo/create/content.go:179 +0x51c
github.com/gohugoio/hugo/create.NewContent.func1()
	github.com/gohugoio/hugo/create/content.go:92 +0x268
github.com/gohugoio/hugo/create.NewContent(0x140008d4640, {0x0, 0x0}, {0x16f8efa81, 0x15}, 0x0)
	github.com/gohugoio/hugo/create/content.go:106 +0x480
github.com/gohugoio/hugo/commands.newNewCommand.func1({0x0?, 0x0?}, 0x0?, 0x140004df900, {0x14000481d80, 0x0?, 0x0?})
	github.com/gohugoio/hugo/commands/new.go:60 +0x160
github.com/gohugoio/hugo/commands.(*simpleCommand).Run(0x0?, {0x104204e48?, 0x1056619e0?}, 0x0?, {0x14000481d80?, 0x2edc75d200000000?, 0x14000abf9f8?})
	github.com/gohugoio/hugo/commands/commandeer.go:618 +0x48
github.com/bep/simplecobra.(*Commandeer).compile.func1(0x1400097ce00?, {0x14000481d80?, 0x4?, 0x1022aedfc?})
	github.com/bep/simplecobra@v0.4.0/simplecobra.go:113 +0x54
github.com/spf13/cobra.(*Command).execute(0x140007f2f08, {0x14000481d40, 0x1, 0x1})
	github.com/spf13/cobra@v1.8.0/command.go:983 +0x840
github.com/spf13/cobra.(*Command).ExecuteC(0x14000967508)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).ExecuteContextC(...)
	github.com/spf13/cobra@v1.8.0/command.go:1048
github.com/bep/simplecobra.(*Exec).Execute(0x1400080ecc8, {0x104204e48?, 0x1056619e0?}, {0x140003e7780?, 0x103d8d7e0?, 0x10055b00c?})
	github.com/bep/simplecobra@v0.4.0/simplecobra.go:155 +0xb4
github.com/gohugoio/hugo/commands.Execute({0x1400019c490, 0x2, 0x2})
	github.com/gohugoio/hugo/commands/commandeer.go:68 +0x284
main.main()
	github.com/gohugoio/hugo/main.go:25 +0x70
```

**Comment by pawelgrzybek** [comment]
@bep I am not sure on which version it was fixed, but the issue is no longer there. I can successfully run `hugo new posts/2024-10-25-it-just-woks` and it build a new post based on my archetype successfully.

I am not sure if the fix was intentional or implicitly resolved by doing some other changes, so I will leave that with you to close the issue.

Thank you 🤗

**Comment by jmooring** [comment]
This has _not_ been fixed. The problem occurs with v0.123.0 and later when the date is in the future. For example:

```text
hugo new posts/2050-12-31-test
```

**Comment by martinflorek** [comment]
> when the date is in the future

Thanks, this saved me after hours of debugging this panic! I have upgraded from v0.121.1 to the current v0.140.1 and this was the last upgrade problem.

Is this bug blocked by something else?

**Comment by justuswilhelm** [comment]
Currently, I'm using hugo v0.147.3 on NixOS. What's funny is that this issue is timezone sensitive. I live in JST. At 8:59, I can't create a post, when the clock turns 9:00, I can suddenly create posts. Quite an entertaining issue!

Here's a stack trace that shows what happens when you create a post with a future date (or before 9:00):

```console
$hugo version
hugo v0.147.3+extended+withdeploy darwin/arm64 BuildDate=unknown VendorInfo=nixpkgs
$hugo new content/posts/2025-08-27-(random)/index.md
panic: [BUG] no Page found for "/Users/debian/projects/personal-website/content/posts/2025-08-27-10949/index.md"

goroutine 1 [running]:
github.com/gohugoio/hugo/create.(*contentBuilder).applyArcheType(0x1400087c3c0, {0x14000054780, 0x4f}, {0x1035cd5a0, 0x140000216c0})
        github.com/gohugoio/hugo/create/content.go:275 +0x2ac
github.com/gohugoio/hugo/create.(*contentBuilder).buildFile(0x1400087c3c0)
        github.com/gohugoio/hugo/create/content.go:244 +0x168
github.com/gohugoio/hugo/create.NewContent.func1()
        github.com/gohugoio/hugo/create/content.go:105 +0x1dc
github.com/gohugoio/hugo/create.NewContent(0x14000635080, {0x0, 0x0}, {0x16f4f70f1, 0x27}, 0x0)
        github.com/gohugoio/hugo/create/content.go:108 +0x478
github.com/gohugoio/hugo/commands.newNewCommand.func1({0x0?, 0x0?}, 0x0?, 0x14000248c60, {0x140008836d0, 0x0?, 0x0?})
        github.com/gohugoio/hugo/commands/new.go:60 +0x168
github.com/gohugoio/hugo/commands.(*simpleCommand).Run(0x0?, {0x1035bddc8?, 0x104e0d740?}, 0x0?, {0x140008836d0?, 0x8c45ce3513800bd9?, 0x140009a79f0?})
        github.com/gohugoio/hugo/commands/commandeer.go:649 +0x48
github.com/bep/simplecobra.(*Commandeer).compile.func1(0x140001e7c00?, {0x140008836d0?, 0x4?, 0x10273c2b1?})
        github.com/bep/simplecobra@v0.6.0/simplecobra.go:113 +0x54
github.com/spf13/cobra.(*Command).execute(0x14000a5f208, {0x14000883690, 0x1, 0x1})
        github.com/spf13/cobra@v1.9.1/command.go:1015 +0x844
github.com/spf13/cobra.(*Command).ExecuteC(0x1400085d808)
        github.com/spf13/cobra@v1.9.1/command.go:1148 +0x384
github.com/spf13/cobra.(*Command).ExecuteContextC(...)
        github.com/spf13/cobra@v1.9.1/command.go:1080
github.com/bep/simplecobra.(*Exec).Execute(0x140005a2958, {0x1035bddc8?, 0x104e0d740?}, {0x1400038ff00?, 0x10308d140?, 0x10094c0c4?})
        github.com/bep/simplecobra@v0.6.0/simplecobra.go:155 +0xb4
github.com/gohugoio/hugo/commands.Execute({0x1400004e5e0, 0x2, 0x2})
        github.com/gohugoio/hugo/commands/commandeer.go:68 +0x27c
main.main()
        github.com/gohugoio/hugo/main.go:25 +0x70
```

It's surprising to see that this issue persists, especially since @jmooring closed my [original issue](https://github.com/gohugoio/hugo/issues/11908). I want to see if I can make a unit test that can reproduce this issue.

For now, I will not do any creative writing before 9:00 😆

**Comment by justuswilhelm** [comment]
Here's how to reproduce this issue, provided we are not in 2050:

```patch
diff --git a/testscripts/commands/new_content_archetypedir.txt b/testscripts/commands/new_content_archetypedir.txt
index ccd85c999..7e4f2ac5a 100644
--- a/testscripts/commands/new_content_archetypedir.txt
+++ b/testscripts/commands/new_content_archetypedir.txt
@@ -5,6 +5,16 @@ grep 'Site Lang: en' content/post/first-post/index.md
 grep 'Site Lang: no' content/post/first-post/index.no.md
 grep 'A text file.' content/post/first-post/file.txt
 
+# This will work fine, as the date is in the past
+hugo new content --kind mybundle post/2024-12-31-this-works/index.md
+cat content/post/2024-12-31-this-works/index.md
+grep 'This Works' content/post/2024-12-31-this-works/index.md
+
+# This breaks, the date is in the future
+hugo new content --kind mybundle post/2050-12-31-this-breaks/index.md
+# Crashes before we can grep
+grep 'This Breaks' content/post/2050-12-31-this-breaks/index.md
+
 -- hugo.toml --
 baseURL = "http://example.org/"
 [languages]
@@ -14,6 +24,8 @@ weight = 1
 [languages.no]
 languageName = "Norsk"
 weight = 2
+[frontmatter]
+publishDate = [":filename"]
 
 -- archetypes/mybundle/index.md --
 ---
```
Run with

```bash
go test -run=Test/new_content_archetypedir -v 
```

Expected output with this test script

```console
=== RUN   TestCommands
=== RUN   TestCommands/new_content_archetypedir
=== PAUSE TestCommands/new_content_archetypedir
=== CONT  TestCommands/new_content_archetypedir
---
title: "2024 12 31 This Works"
date: 2025-08-26T09:32:38+09:00
draft: true
---

    testscript.go:584: WORK=$WORK
        PATH=/var/folders/k8/jnlz0xdn5jd48zttf3ktv7200000gn/T/testscript-main3965700614/bin:/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/bin:/etc/profiles/per-user/debian/bin:/run/current-system/sw/bin:/nix/var/nix/profiles/default/bin:/Users/debian/.local/bin:/Users/debian/.dotfiles/bin:/Users/debian/.cargo/bin:/Users/debian/.nix-profile/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
        GOTRACEBACK=system
        HOME=$WORK/home
        TMPDIR=$WORK/.tmp
        devnull=/dev/null
        /=/
        :=:
        $=$
        exe=
        HUGO_TESTRUN=true
        HUGO_CACHEDIR=$WORK/hugocache
        XDG_CACHE_HOME=$WORK/xdgcachehome
        SOURCE=/Users/debian/projects/hugo/hugo
        GOVERSION=1.24.3
        
        > mkdir content
        > hugo new content --kind mybundle post/first-post
        [stdout]
        Content dir "$WORK/content/post/first-post" created
        > grep 'First Post' content/post/first-post/index.md
        > grep 'Site Lang: en' content/post/first-post/index.md
        > grep 'Site Lang: no' content/post/first-post/index.no.md
        > grep 'A text file.' content/post/first-post/file.txt
        # This will work fine, as the date is in the past (0.031s)
        > hugo new content --kind mybundle post/2024-12-31-this-works/index.md
        [stdout]
        Content "$WORK/content/post/2024-12-31-this-works/index.md" created
        > cat content/post/2024-12-31-this-works/index.md
        > grep 'This Works' content/post/2024-12-31-this-works/index.md
        # This breaks, the date is in the future (0.032s)
        > hugo new content --kind mybundle post/2050-12-31-this-breaks/index.md
        [stderr]
        panic: [BUG] no Page found for "$WORK/content/post/2050-12-31-this-breaks/index.md"
        
        goroutine 1 gp=0x140000021c0 m=8 mp=0x14000500808 [running]:
        panic({0x1029ebdc0?, 0x140001b7b20?})
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/panic.go:811 +0x154 fp=0x140007073f0 sp=0x14000707340 pc=0x10105a574
        github.com/gohugoio/hugo/create.(*contentBuilder).applyArcheType(0x14000656300, {0x14000148320, 0x9e}, {0x0, 0x0})
        	/Users/debian/projects/hugo/hugo/create/content.go:275 +0x2ac fp=0x140007074c0 sp=0x140007073f0 pc=0x1022e222c
        github.com/gohugoio/hugo/create.(*contentBuilder).buildFile(0x14000656300)
        	/Users/debian/projects/hugo/hugo/create/content.go:244 +0x168 fp=0x14000707580 sp=0x140007074c0 pc=0x1022e1b08
        github.com/gohugoio/hugo/create.NewContent.func1()
        	/Users/debian/projects/hugo/hugo/create/content.go:105 +0x1dc fp=0x14000707620 sp=0x14000707580 pc=0x1022e0d2c
        github.com/gohugoio/hugo/create.NewContent(0x1400055fb80, {0x16ee1b90f, 0x8}, {0x16ee1b918, 0x24}, 0x0)
        	/Users/debian/projects/hugo/hugo/create/content.go:108 +0x478 fp=0x140007077d0 sp=0x14000707620 pc=0x1022e0a88
        github.com/gohugoio/hugo/commands.newNewCommand.func1({0x0?, 0x0?}, 0x0?, 0x140001ffb80, {0x14000164d50, 0x0?, 0x0?})
        	/Users/debian/projects/hugo/hugo/commands/new.go:60 +0x168 fp=0x14000707850 sp=0x140007077d0 pc=0x102337078
        github.com/gohugoio/hugo/commands.(*simpleCommand).Run(0x0?, {0x102ceef18?, 0x103eea0a0?}, 0x0?, {0x14000164d50?, 0xae46be59f734fbe?, 0x14000621800?})
        	/Users/debian/projects/hugo/hugo/commands/commandeer.go:649 +0x48 fp=0x140007078a0 sp=0x14000707850 pc=0x102323738
        github.com/bep/simplecobra.(*Commandeer).compile.func1(0x140001ab000?, {0x14000164d50?, 0x4?, 0x1023b0162?})
        	/Users/debian/go/pkg/mod/github.com/bep/simplecobra@v0.6.1/simplecobra.go:113 +0x54 fp=0x14000707900 sp=0x140007078a0 pc=0x1013fcac4
        github.com/spf13/cobra.(*Command).execute(0x140004fc008, {0x14000164cf0, 0x3, 0x3})
        	/Users/debian/go/pkg/mod/github.com/spf13/cobra@v1.9.1/command.go:1015 +0x844 fp=0x14000707a90 sp=0x14000707900 pc=0x1013eed74
        github.com/spf13/cobra.(*Command).ExecuteC(0x140003ac008)
        	/Users/debian/go/pkg/mod/github.com/spf13/cobra@v1.9.1/command.go:1148 +0x384 fp=0x14000707b80 sp=0x14000707a90 pc=0x1013ef554
        github.com/spf13/cobra.(*Command).ExecuteContextC(...)
        	/Users/debian/go/pkg/mod/github.com/spf13/cobra@v1.9.1/command.go:1080
        github.com/bep/simplecobra.(*Exec).Execute(0x1400007b270, {0x102ceef18?, 0x103eea0a0?}, {0x1400003a250?, 0x140002799c0?, 0x1023b3b90?})
        	/Users/debian/go/pkg/mod/github.com/bep/simplecobra@v0.6.1/simplecobra.go:155 +0xb4 fp=0x14000707c10 sp=0x14000707b80 pc=0x1013fcc04
        github.com/gohugoio/hugo/commands.Execute({0x1400003a250, 0x5, 0x5})
        	/Users/debian/projects/hugo/hugo/commands/commandeer.go:68 +0x27c fp=0x14000707d00 sp=0x14000707c10 pc=0x10231ff7c
        main.main.TestMain.func1()
        	/Users/debian/projects/hugo/hugo/main_test.go:62 +0x54 fp=0x14000707d50 sp=0x14000707d00 pc=0x10235d6e4
        github.com/rogpeppe/go-internal/testscript.Main({0x102cde468, 0x1400037abe0}, 0x14000621f08)
        	/Users/debian/go/pkg/mod/github.com/rogpeppe/go-internal@v1.14.1/testscript/exe.go:57 +0xe8 fp=0x14000707da0 sp=0x14000707d50 pc=0x1023527e8
        github.com/gohugoio/hugo.TestMain(...)
        	/Users/debian/projects/hugo/hugo/main_test.go:59
        main.main()
        	_testmain.go:51 +0x134 fp=0x14000707f40 sp=0x14000707da0 pc=0x10235d554
        runtime.main()
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/proc.go:283 +0x284 fp=0x14000707fd0 sp=0x14000707f40 pc=0x1010252d4
        runtime.goexit({})
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/asm_arm64.s:1223 +0x4 fp=0x14000707fd0 sp=0x14000707fd0 pc=0x101062f34
        
        goroutine 2 gp=0x14000002700 m=nil [force gc (idle)]:
        runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/proc.go:435 +0xc8 fp=0x14000076f90 sp=0x14000076f70 pc=0x10105a9d8
        runtime.goparkunlock(...)
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/proc.go:441
        runtime.forcegchelper()
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/proc.go:348 +0xb8 fp=0x14000076fd0 sp=0x14000076f90 pc=0x101025628
        runtime.goexit({})
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/asm_arm64.s:1223 +0x4 fp=0x14000076fd0 sp=0x14000076fd0 pc=0x101062f34
        created by runtime.init.7 in goroutine 1
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/proc.go:336 +0x24
        
        goroutine 3 gp=0x14000002c40 m=nil [GC sweep wait]:
        runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/proc.go:435 +0xc8 fp=0x14000077760 sp=0x14000077740 pc=0x10105a9d8
        runtime.goparkunlock(...)
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/proc.go:441
        runtime.bgsweep(0x1400003e200)
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/mgcsweep.go:316 +0x108 fp=0x140000777b0 sp=0x14000077760 pc=0x10100e2e8
        runtime.gcenable.gowrap1()
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/mgc.go:204 +0x28 fp=0x140000777d0 sp=0x140000777b0 pc=0x1010020f8
        runtime.goexit({})
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/asm_arm64.s:1223 +0x4 fp=0x140000777d0 sp=0x140000777d0 pc=0x101062f34
        created by runtime.gcenable in goroutine 1
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/mgc.go:204 +0x6c
        
        goroutine 4 gp=0x14000002e00 m=nil [GC scavenge wait]:
        runtime.gopark(0x22d210?, 0x6553f100?, 0x0?, 0x0?, 0x0?)
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/proc.go:435 +0xc8 fp=0x14000077f60 sp=0x14000077f40 pc=0x10105a9d8
        runtime.goparkunlock(...)
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/proc.go:441
        runtime.(*scavengerState).park(0x103eb72c0)
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/mgcscavenge.go:425 +0x5c fp=0x14000077f90 sp=0x14000077f60 pc=0x10100bd8c
        runtime.bgscavenge(0x1400003e200)
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/mgcscavenge.go:658 +0xac fp=0x14000077fb0 sp=0x14000077f90 pc=0x10100c32c
        runtime.gcenable.gowrap2()
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/mgc.go:205 +0x28 fp=0x14000077fd0 sp=0x14000077fb0 pc=0x101002098
        runtime.goexit({})
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/asm_arm64.s:1223 +0x4 fp=0x14000077fd0 sp=0x14000077fd0 pc=0x101062f34
        created by runtime.gcenable in goroutine 1
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/mgc.go:205 +0xac
        
        goroutine 5 gp=0x14000003340 m=nil [finalizer wait]:
        runtime.gopark(0x140000765c8?, 0x101a52e9c?, 0xe8?, 0x65?, 0x101025554?)
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/proc.go:435 +0xc8 fp=0x14000076590 sp=0x14000076570 pc=0x10105a9d8
        runtime.runfinq()
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/mfinal.go:196 +0x108 fp=0x140000767d0 sp=0x14000076590 pc=0x1010010f8
        runtime.goexit({})
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/asm_arm64.s:1223 +0x4 fp=0x140000767d0 sp=0x140000767d0 pc=0x101062f34
        created by runtime.createfing in goroutine 1
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/mfinal.go:166 +0x80
        
        goroutine 6 gp=0x14000003880 m=nil [GC worker (idle)]:
        runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/proc.go:435 +0xc8 fp=0x14000078710 sp=0x140000786f0 pc=0x10105a9d8
        runtime.gcBgMarkWorker(0x1400010a0e0)
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/mgc.go:1423 +0xdc fp=0x140000787b0 sp=0x14000078710 pc=0x10100458c
        runtime.gcBgMarkStartWorkers.gowrap1()
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/mgc.go:1339 +0x28 fp=0x140000787d0 sp=0x140000787b0 pc=0x101004478
        runtime.goexit({})
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/asm_arm64.s:1223 +0x4 fp=0x140000787d0 sp=0x140000787d0 pc=0x101062f34
        created by runtime.gcBgMarkStartWorkers in goroutine 1
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/mgc.go:1339 +0x140
        
        goroutine 17 gp=0x14000092380 m=nil [GC worker (idle)]:
        runtime.gopark(0x86af3670159?, 0x3?, 0xb2?, 0x76?, 0x0?)
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/proc.go:435 +0xc8 fp=0x14000072710 sp=0x140000726f0 pc=0x10105a9d8
        runtime.gcBgMarkWorker(0x1400010a0e0)
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/mgc.go:1423 +0xdc fp=0x140000727b0 sp=0x14000072710 pc=0x10100458c
        runtime.gcBgMarkStartWorkers.gowrap1()
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/mgc.go:1339 +0x28 fp=0x140000727d0 sp=0x140000727b0 pc=0x101004478
        runtime.goexit({})
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/asm_arm64.s:1223 +0x4 fp=0x140000727d0 sp=0x140000727d0 pc=0x101062f34
        created by runtime.gcBgMarkStartWorkers in goroutine 1
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/mgc.go:1339 +0x140
        
        goroutine 33 gp=0x14000484000 m=nil [GC worker (idle)]:
        runtime.gopark(0x86af3670376?, 0x1400013c300?, 0x1b?, 0xa?, 0x0?)
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/proc.go:435 +0xc8 fp=0x1400048a710 sp=0x1400048a6f0 pc=0x10105a9d8
        runtime.gcBgMarkWorker(0x1400010a0e0)
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/mgc.go:1423 +0xdc fp=0x1400048a7b0 sp=0x1400048a710 pc=0x10100458c
        runtime.gcBgMarkStartWorkers.gowrap1()
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/mgc.go:1339 +0x28 fp=0x1400048a7d0 sp=0x1400048a7b0 pc=0x101004478
        runtime.goexit({})
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/asm_arm64.s:1223 +0x4 fp=0x1400048a7d0 sp=0x1400048a7d0 pc=0x101062f34
        created by runtime.gcBgMarkStartWorkers in goroutine 1
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/mgc.go:1339 +0x140
        
        goroutine 7 gp=0x14000003a40 m=nil [GC worker (idle)]:
        runtime.gopark(0x86af366fb53?, 0x3?, 0x27?, 0xb6?, 0x0?)
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/proc.go:435 +0xc8 fp=0x14000078f10 sp=0x14000078ef0 pc=0x10105a9d8
        runtime.gcBgMarkWorker(0x1400010a0e0)
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/mgc.go:1423 +0xdc fp=0x14000078fb0 sp=0x14000078f10 pc=0x10100458c
        runtime.gcBgMarkStartWorkers.gowrap1()
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/mgc.go:1339 +0x28 fp=0x14000078fd0 sp=0x14000078fb0 pc=0x101004478
        runtime.goexit({})
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/asm_arm64.s:1223 +0x4 fp=0x14000078fd0 sp=0x14000078fd0 pc=0x101062f34
        created by runtime.gcBgMarkStartWorkers in goroutine 1
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/mgc.go:1339 +0x140
        
        goroutine 18 gp=0x14000092540 m=nil [GC worker (idle)]:
        runtime.gopark(0x103eebf20?, 0x3?, 0xa1?, 0xe2?, 0x0?)
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/proc.go:435 +0xc8 fp=0x140000aef10 sp=0x140000aeef0 pc=0x10105a9d8
        runtime.gcBgMarkWorker(0x1400010a0e0)
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/mgc.go:1423 +0xdc fp=0x140000aefb0 sp=0x140000aef10 pc=0x10100458c
        runtime.gcBgMarkStartWorkers.gowrap1()
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/mgc.go:1339 +0x28 fp=0x140000aefd0 sp=0x140000aefb0 pc=0x101004478
        runtime.goexit({})
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/asm_arm64.s:1223 +0x4 fp=0x140000aefd0 sp=0x140000aefd0 pc=0x101062f34
        created by runtime.gcBgMarkStartWorkers in goroutine 1
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/mgc.go:1339 +0x140
        
        goroutine 34 gp=0x140004841c0 m=nil [GC worker (idle)]:
        runtime.gopark(0x86af366254b?, 0x3?, 0x3?, 0xbb?, 0x0?)
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/proc.go:435 +0xc8 fp=0x140000aaf10 sp=0x140000aaef0 pc=0x10105a9d8
        runtime.gcBgMarkWorker(0x1400010a0e0)
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/mgc.go:1423 +0xdc fp=0x140000aafb0 sp=0x140000aaf10 pc=0x10100458c
        runtime.gcBgMarkStartWorkers.gowrap1()
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/mgc.go:1339 +0x28 fp=0x140000aafd0 sp=0x140000aafb0 pc=0x101004478
        runtime.goexit({})
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/asm_arm64.s:1223 +0x4 fp=0x140000aafd0 sp=0x140000aafd0 pc=0x101062f34
        created by runtime.gcBgMarkStartWorkers in goroutine 1
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/mgc.go:1339 +0x140
        
        goroutine 8 gp=0x14000003c00 m=nil [GC worker (idle)]:
        runtime.gopark(0x86af36703a0?, 0x3?, 0x7a?, 0x20?, 0x0?)
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/proc.go:435 +0xc8 fp=0x14000079710 sp=0x140000796f0 pc=0x10105a9d8
        runtime.gcBgMarkWorker(0x1400010a0e0)
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/mgc.go:1423 +0xdc fp=0x140000797b0 sp=0x14000079710 pc=0x10100458c
        runtime.gcBgMarkStartWorkers.gowrap1()
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/mgc.go:1339 +0x28 fp=0x140000797d0 sp=0x140000797b0 pc=0x101004478
        runtime.goexit({})
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/asm_arm64.s:1223 +0x4 fp=0x140000797d0 sp=0x140000797d0 pc=0x101062f34
        created by runtime.gcBgMarkStartWorkers in goroutine 1
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/mgc.go:1339 +0x140
        
        goroutine 19 gp=0x14000092700 m=nil [GC worker (idle)]:
        runtime.gopark(0x86af3661c81?, 0x3?, 0x98?, 0x28?, 0x0?)
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/proc.go:435 +0xc8 fp=0x14000073710 sp=0x140000736f0 pc=0x10105a9d8
        runtime.gcBgMarkWorker(0x1400010a0e0)
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/mgc.go:1423 +0xdc fp=0x140000737b0 sp=0x14000073710 pc=0x10100458c
        runtime.gcBgMarkStartWorkers.gowrap1()
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/mgc.go:1339 +0x28 fp=0x140000737d0 sp=0x140000737b0 pc=0x101004478
        runtime.goexit({})
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/asm_arm64.s:1223 +0x4 fp=0x140000737d0 sp=0x140000737d0 pc=0x101062f34
        created by runtime.gcBgMarkStartWorkers in goroutine 1
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/mgc.go:1339 +0x140
        
        goroutine 9 gp=0x14000484e00 m=nil [chan receive]:
        runtime.gopark(0x140004bd9a0?, 0x14000600078?, 0x48?, 0xaf?, 0x1012230c8?)
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/proc.go:435 +0xc8 fp=0x1400048aef0 sp=0x1400048aed0 pc=0x10105a9d8
        runtime.chanrecv(0x1400010a540, 0x0, 0x1)
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/chan.go:664 +0x42c fp=0x1400048af70 sp=0x1400048aef0 pc=0x100ff3aec
        runtime.chanrecv1(0x0?, 0x101062f34?)
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/chan.go:506 +0x14 fp=0x1400048afa0 sp=0x1400048af70 pc=0x100ff3684
        runtime.unique_runtime_registerUniqueMapCleanup.func2(...)
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/mgc.go:1796
        runtime.unique_runtime_registerUniqueMapCleanup.gowrap1()
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/mgc.go:1799 +0x3c fp=0x1400048afd0 sp=0x1400048afa0 pc=0x10100531c
        runtime.goexit({})
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/asm_arm64.s:1223 +0x4 fp=0x1400048afd0 sp=0x1400048afd0 pc=0x101062f34
        created by unique.runtime_registerUniqueMapCleanup in goroutine 1
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/mgc.go:1794 +0x78
        
        goroutine 10 gp=0x14000093180 m=nil [select]:
        runtime.gopark(0x1400048dfa8?, 0x2?, 0x0?, 0x0?, 0x1400048df8c?)
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/proc.go:435 +0xc8 fp=0x140000b1e20 sp=0x140000b1e00 pc=0x10105a9d8
        runtime.selectgo(0x140000b1fa8, 0x1400048df88, 0x0?, 0x0, 0x0?, 0x1)
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/select.go:351 +0x6c4 fp=0x140000b1f50 sp=0x140000b1e20 pc=0x101038d34
        github.com/gohugoio/hugo/cache/dynacache.(*Cache).start.func1()
        	/Users/debian/projects/hugo/hugo/cache/dynacache/dynacache.go:315 +0x84 fp=0x140000b1fd0 sp=0x140000b1f50 pc=0x101d26f74
        runtime.goexit({})
        	/nix/store/ps3admpzmc1ryvn9q7sw5xfd94dkrb3f-go-1.24.3/share/go/src/runtime/asm_arm64.s:1223 +0x4 fp=0x140000b1fd0 sp=0x140000b1fd0 pc=0x101062f34
        created by github.com/gohugoio/hugo/cache/dynacache.(*Cache).start in goroutine 1
        	/Users/debian/projects/hugo/hugo/cache/dynacache/dynacache.go:313 +0x9c
        [exit status 2]
        FAIL: testscripts/commands/new_content_archetypedir.txt:14: unexpected command failure
        
--- FAIL: TestCommands (0.00s)
    --- FAIL: TestCommands/new_content_archetypedir (0.62s)
=== RUN   TestUnfinished
--- PASS: TestUnfinished (0.00s)
=== RUN   TestWithdeploy
--- PASS: TestWithdeploy (0.00s)
FAIL
exit status 1
FAIL	github.com/gohugoio/hugo	1.696s

```

**Comment by pawelgrzybek** [comment]
Thank you @bep
