### ISSUE TITLE
Adding --minfy causes unexpected "/js/jquery.tagcloud.js" in binding

### ISSUE THREAD

**Issue by shadycuz** [gohugoio/hugo#8693]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.84.1-4BD65E22 linux/amd64 BuildDate=2021-06-24T11:44:23Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

I think this is the latest release. It did not do this on `0.79`.

The code from my `partials/footer.html`.
```js
<!-- jquery.tagcloud.js -->
<script>
    // only load tagcloud.js in tag.html
    if($('#tag_cloud').length !== 0){
        async("/js/jquery.tagcloud.js",function(){
            $.fn.tagcloud.defaults = {
                //size: {start: 1, end: 1, unit: 'em'},
                color: {start: '#bbbbee', end: '#0085a1'},
            };
            $('#tag_cloud a').tagcloud();
        })
    }
</script>
```

The cmd and err.
```sh
shadycuz-> hugo --gc --minify
Start building sites … 
hugo v0.84.1-4BD65E22 linux/amd64 BuildDate=2021-06-24T11:44:23Z VendorInfo=gohugoio
Page.URL is deprecated and will be removed in a future release. Use .Permalink or .RelPermalink. If what you want is the front matter URL value, use .Params.url
ERROR 2021/06/26 07:06:29 unexpected "/js/jquery.tagcloud.js" in binding on line 606 and column 23
    4:         async("/js/jquery.tagcloud.js",function(){
                     ^
ERROR 2021/06/26 07:06:29 unexpected "/js/jquery.tagcloud.js" in binding on line 736 and column 23
    4:         async("/js/jquery.tagcloud.js",function(){
                     ^
ERROR 2021/06/26 07:06:29 unexpected "/js/jquery.tagcloud.js" in binding on line 842 and column 23
    4:         async("/js/jquery.tagcloud.js",function(){
                     ^
ERROR 2021/06/26 07:06:29 unexpected "/js/jquery.tagcloud.js" in binding on line 691 and column 23
    4:         async("/js/jquery.tagcloud.js",function(){
                     ^
Total in 193 ms
Error: Error building site: failed to render pages: unexpected "/js/jquery.tagcloud.js" in binding on line 899 and column 23
    4:         async("/js/jquery.tagcloud.js",function(){
```

**Comment by pamubay** [comment]
This is upstream issue from [`tdewolff/minify`](https://github.com/tdewolff/minify).

`minify` failed if found js function named `async`. 
Related issue in upstream [JS: unable to parse if a function is named "async"](https://github.com/tdewolff/minify/issues/406).

Already fixed in [`tdewolff/minify v2.9.17`](https://github.com/tdewolff/minify/releases/tag/v2.9.17)

Hugo still use `tdewolff/minify v2.9.16`

**Comment by carlmjohnson** [comment]
To be clear, your JS is technically okay, but they made `async` a keyword in later versions of JS, so naming a function `async` is an invitation for bugs that creep in when programs don't consider that `async` could be used as a normal variable name. I suggest the following edit to your footer to prevent future bugs:

```html
<script>
    // only load tagcloud.js in tag.html
    if($('#tag_cloud').length !== 0){
        window.async("/js/jquery.tagcloud.js",function(){
            $.fn.tagcloud.defaults = {
                //size: {start: 1, end: 1, unit: 'em'},
                color: {start: '#bbbbee', end: '#0085a1'},
            };
            $('#tag_cloud a').tagcloud();
        })
    }
</script>
```

`window.whatever` is technically the same as `whatever`, but `window.async` is less likely to hit unexpected bugs like this.

**Comment by robsonsobral** [comment]
Hi!

I just want to let you know that the minification of conditional chaining is still broken.
