### ISSUE TITLE
Keep release notes in sync: gohugo.io/news vs. github.com/gohugoio/hugo/releases

### ISSUE THREAD

**Issue by tdelmas** [gohugoio/hugo#9136]
In https://github.com/gohugoio/hugo/releases/tag/v0.89.0

The following sentence is missing a link (and has a typo):

> - We have updated the Twitter shortcode to use Twitter's new API. See [thiss issue] for details.

Emphasis on **[thiss issue]**

**Comment by jmooring** [comment]
This was fixed a few days ago.

<img width="70%" alt="Screen capture" src="https://user-images.githubusercontent.com/335669/140576218-7af45cc1-5dc8-499f-ac3e-3dab4fbdd8b6.png">

Once a release occurs, the documentation is maintained in https://github.com/gohugoio/hugoDocs.

**Comment by tdelmas** [comment]
The typo "[thiss issue]" on the page https://github.com/gohugoio/hugo/releases/tag/v0.89.0 is **not** corrected.

Yes, the documentation (https://gohugo.io) is in https://github.com/gohugoio/hugoDocs and the corresponding page https://gohugo.io/news/0.89.0-relnotes/ was updated.

But here the release notes here were not fixed. 

Maybe the releases notes shouldn't be duplicated, but it's another subject. Also, the documentation on https://gohugo.io often refer to the release pages here instead of the release news on the same website, so people are redirected to that webpage.

Please consider reopening this issue (or simply correcting the releases notes on https://github.com/gohugoio/hugo/releases/tag/v0.89.0 🙂

**Comment by jmooring** [comment]
@tdelmas 

I apologize.

I recognized that I had already fixed the typo in gohugoio/hugoDocs, and then ignored the details in your description.

So, the release notes exist in three places:
1. <https://github.com/gohugoio/hugo/tree/master/docs/content/en/news>
2. <https://github.com/gohugoio/hugoDocs/tree/master/content/en/news>
3. <https://github.com/gohugoio/hugo/releases/tag/vn.n.n>

Documentation changes related to unreleased code changes are maintained in gohugoio/hugo, then pushed to gohugoio/hugoDocs upon release.

Documentation changes related to released code (example: clarifying what a particular function does) are maintained in gohugoio/hugoDocs, then pulled back into gohugoio/hugo. I have not investigated when the changes are pulled back into gohugoio/hugo or how it happens.

We use [goreleaser](https://github.com/goreleaser/goreleaser/) to automate a number of the release tasks, including the generation of release notes. Again, I have not investigate the process, but we end up with the release notes in three places. 

After release, we don't need to worry about what's in gohugoio/hugo, because the "source" is now in gohugoio/hugoDocs. But that leaves us with an orphaned copy of the release notes at gohugoio/hugo/releases/tag/vn.n.n.

Options:

1. When we find an error in the release notes, manually make the changes in both locations. Yuck.
2. Treat gohugoio/hugo/releases/tag/vn.n.n as the "source", and access it via `getJSON` when rebuilding the docs site (see `body` in [this API response](https://api.github.com/repos/gohugoio/hugo/releases/tags/v0.89.0)).

For now, I've updated gohugoio/hugo/releases/tag/v0.89.0 to match gohugoio/hugoDocs

**Comment by tdelmas** [comment]
Thank you for the fix, and even more for the detailed explanation!

Another solution could be to just replace two of the three places with a simple link? (I've the feeling that next to the download link, it's the best place to keep the detailed notes)

**Comment by bep** [comment]
>So, the release notes exist in three places:

No, it's 2 places. The 2 docs branches gets merged periodically.

Whatever we do should make this simpler, not harder.

So, in my head that currently either means either:

1. We announce on GitHub only
2. We accept that there are errors in the release notes.

**Comment by jmooring** [comment]
>So, in my head that currently either means either:
>
> 1. We announce on GitHub only
> 2. We accept that there are errors in the release notes.

I think there is value in driving visits to <https://gohugo.io/news/> and providing details instead of a link back to <https://github.com/gohugoio/hugo/releases>. 

The rate limits of GitHub's API prevent reliable use of shortcode to pull the data while building the docs site, so I'm back to:

> When we find an error in the release notes, manually make the changes in both locations.

I will try to keep an eye on this.
